version: '3'

services:
  mysqldb:
    image: mysql
    volumes:
      - /home/aah/tmp:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  recipe:
    image: aahouzi/springbootdocker
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
