version: '3'

services:
  mysqldb:
    image: mysql
    volumes:
      - aahTemp:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - database_net
    deploy:
      replicas: 1
  recipe:
    image: aahouzi/springbootdocker
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - database_net
    deploy:
      replicas: 3
networks:
  database_net:
    driver: overlay