version: '3'

services:
  mysqldb:
    image: mysql
    volumes:
      - aahTemp:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - database_net
    deploy:
      replicas: 1
  recipe:
    image: aahouzi/springbootdocker
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
    networks:
      - database_net
    deploy:
      replicas: 1
volumes:
  aahTemp:
networks:
  database_net:
    driver: overlay